err:winediag:SECUR32_initNTLMSP ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.
162 INFO: PyInstaller: 3.3.1
163 INFO: Python: 3.4.4
163 INFO: Platform: Windows-XP-5.1.2600-SP3
165 INFO: wrote Z:\p2e\card.spec
172 INFO: UPX is not available.
172 INFO: Removing temporary files and cleaning cache in C:\users\root\Application Data\pyinstaller
181 INFO: Extending PYTHONPATH with paths
['Z:\\p2e\\workingdir\\1516410030954', 'Z:\\p2e']
182 INFO: checking Analysis
182 INFO: Building Analysis because out00-Analysis.toc is non existent
182 INFO: Initializing module dependency graph...
191 INFO: Initializing module graph hooks...
195 INFO: Analyzing base_library.zip ...
7604 INFO: Processing pre-find module path hook   distutils
10691 INFO: running Analysis out00-Analysis.toc
11183 INFO: Caching module hooks...
11197 INFO: Analyzing Z:\p2e\workingdir\1516410030954\card.py
11332 INFO: Loading module hooks...
11332 INFO: Loading module hook "hook-pydoc.py"...
11334 INFO: Loading module hook "hook-xml.py"...
11919 INFO: Loading module hook "hook-encodings.py"...
12094 INFO: Loading module hook "hook-distutils.py"...
12126 INFO: Looking for ctypes DLLs
12188 INFO: Analyzing run-time hooks ...
12202 INFO: Looking for dynamic libraries
12433 INFO: Looking for eggs
12433 INFO: Using Python library c:\Python34\python34.dll
12433 INFO: Found binding redirects: 
[]
12438 INFO: Warnings written to ./workingdir/1516410030954/build/card\warncard.txt
12545 INFO: Graph cross-reference written to ./workingdir/1516410030954/build/card\xref-card.html
12578 INFO: checking PYZ
12579 INFO: Building PYZ because out00-PYZ.toc is non existent
12579 INFO: Building PYZ (ZlibArchive) ./workingdir/1516410030954/build/card\out00-PYZ.pyz
13983 INFO: Building PYZ (ZlibArchive) ./workingdir/1516410030954/build/card\out00-PYZ.pyz completed successfully.
14013 INFO: checking PKG
14014 INFO: Building PKG because out00-PKG.toc is non existent
14014 INFO: Building PKG (CArchive) out00-PKG.pkg
14033 INFO: Updating manifest in C:\users\root\Application Data\pyinstaller\bincache00_py34_32bit\python34.dll
14034 INFO: Updating resource type 24 name 2 language 1033
16019 INFO: Building PKG (CArchive) out00-PKG.pkg completed successfully.
16025 INFO: Bootloader c:\Python34\lib\site-packages\PyInstaller\bootloader\Windows-32bit\run.exe
16026 INFO: checking EXE
16026 INFO: Building EXE because out00-EXE.toc is non existent
16026 INFO: Building EXE from out00-EXE.toc
16029 INFO: SRCPATH [('workingdir\\1516410030954\\additionalicon\\ssss.ico', None)]
16029 INFO: Updating icons from ['workingdir\\1516410030954\\additionalicon\\ssss.ico'] to C:\users\root\Temp\tmp69ddgnd5
Traceback (most recent call last):
  File "C:\Python34\Scripts\pyinstaller-script.py", line 9, in <module>
    load_entry_point('PyInstaller==3.3.1', 'console_scripts', 'pyinstaller')()
  File "c:\Python34\lib\site-packages\PyInstaller\__main__.py", line 94, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "c:\Python34\lib\site-packages\PyInstaller\__main__.py", line 46, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "c:\Python34\lib\site-packages\PyInstaller\building\build_main.py", line 791, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "c:\Python34\lib\site-packages\PyInstaller\building\build_main.py", line 737, in build
    exec(text, spec_namespace)
  File "<string>", line 29, in <module>
  File "c:\Python34\lib\site-packages\PyInstaller\building\api.py", line 420, in __init__
    self.__postinit__()
  File "c:\Python34\lib\site-packages\PyInstaller\building\datastruct.py", line 161, in __postinit__
    self.assemble()
  File "c:\Python34\lib\site-packages\PyInstaller\building\api.py", line 509, in assemble
    icon.CopyIcons(tmpnm, self.icon)
  File "c:\Python34\lib\site-packages\PyInstaller\utils\win32\icon.py", line 166, in CopyIcons
    return CopyIcons_FromIco(dstpath, [srcpath])
  File "c:\Python34\lib\site-packages\PyInstaller\utils\win32\icon.py", line 123, in CopyIcons_FromIco
    for i, f in enumerate(icons):
  File "c:\Python34\lib\site-packages\PyInstaller\utils\win32\icon.py", line 95, in __init__
    entry.fromfile(file)
  File "c:\Python34\lib\site-packages\PyInstaller\utils\win32\icon.py", line 65, in fromfile
    self._fields_ = list(struct.unpack(self._format_, data))
struct.error: unpack requires a bytes object of length 16
